name:
  Build & Deploy to https://github.com/yyj0917/SCENT-YONSEI-WEB (-> Fork한 내
  개인 계정 레포 주소)

on:
  push:
    branches:
      - prod (-> Organiation 레포의 배포를 할 브랜치 (보통은 main branch or
        팀만의 배포전용 브랜치))
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    container: pandoc/latex

    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Prepare output
        shell: sh
        run: |
          # enable extglob and dotglob might not work in sh
          # Use alternative commands for file copying
          rm -rf output
          mkdir output
          # Use find command instead of extglob pattern
          find . -maxdepth 1 -not -path "./output" -not -path "./.git" -not -path "./.github" -exec cp -R {} output/ \;

      - name:
          Push to https://github.com/yyj0917/SCENT-YONSEI-WEB (-> Fork한 내 개인
          계정 레포 주소)
        id: push
        uses: cpina/github-action-push-to-another-repository@v1.7.2
        env:
          API_TOKEN_GITHUB:
            ${{ secrets.SCENT_PAT }} (-> 개인계정에서 personal access token
            기입해야 함. 자세한 방법 밑에서 확인)
        with:
          source-directory: 'output'
          destination-github-username: yyj0917 (-> Fork한 레포 계정 username)
          destination-repository-name: SCENT-YONSEI-WEB (-> Fork한 레포 name)
          user-name: GitHub Actions
          user-email: yyj0917@yonsei.ac.kr (-> Fork한 계정 이메일)
          commit-message: 'Deploy from build: ${{ github.sha }}'
          target-branch: main (-> Fork한 레포에서 vercel에서 배포할 브랜치)

      - name: 'Debug: show cloned dir'
        run: echo "Cloned into $DESTINATION_CLONED_DIRECTORY"
